/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	// But you can create a sidebar manually
	walletSidebar: [
		{
			type: 'doc',
			id: 'wallet/intro',
		},
		{
			type: 'category',
			label: 'Using Pelagus',
			collapsed: false,
			link: { type: 'generated-index' },
			items: [{ type: 'autogenerated', dirName: 'wallet/use-pelagus' }],
		},
	],
	developSidebar: [
		{ type: 'doc', id: 'develop/intro' },
		{
			type: 'category',
			label: 'Getting Started',
			collapsed: false,
			link: { type: 'generated-index' },
			items: [{ type: 'autogenerated', dirName: 'develop/get-started' }],
		},
		{
			type: 'category',
			label: 'How To',
			link: { type: 'generated-index' },
			items: [{ type: 'autogenerated', dirName: 'develop/how-to' }],
		},
		{
			type: 'category',
			label: 'API Reference',
			link: { type: 'generated-index' },
			items: [{ type: 'autogenerated', dirName: 'develop/api' }],
		},
	],
};

module.exports = sidebars;
