apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pelagus-docs
  name: pelagus-docs
  namespace: quai-prod
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pelagus-docs
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pelagus-docs
    spec:
      containers:
      - image: quainetwork/pelagus-docs:0.1.0-pre.0
        imagePullPolicy: IfNotPresent
        name: pelagus-docs
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
